# Generated by Django 3.2.3 on 2021-06-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('idservicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de servicio')),
                ('nomservicio', models.CharField(max_length=100, verbose_name='Nombre de servicio')),
                ('valorservicio', models.CharField(max_length=100, verbose_name='valor servicio por hora')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombreusuario', models.CharField(max_length=16, verbose_name='Nombre de usuario')),
                ('contrausuario', models.CharField(max_length=12, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='usuariomoroso',
            fields=[
                ('idmoroso', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de moroso')),
                ('nombremoroso', models.CharField(max_length=16, verbose_name='Nombre de moroso')),
                ('mesesmoroso', models.CharField(max_length=100, verbose_name='meses de morosidad')),
            ],
        ),
    ]
