# Generated by Django 3.2.3 on 2021-06-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exp3.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariomoroso',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='exp3.usuario'),
            preserve_default=False,
        ),
    ]
